POST http://localhost:8080/api/auth/sign-up
Content-Type: application/json

{
    "username": "gorath7111",
    "email": "gorath@examdwplea212.com",
    "password": "P@ssw0rd!123",
    "accept_terms": true
}

###

PUT http://localhost:8080/api/auth/activation-link
Content-Type: application/json

 {
    "email": "gorath@examdwplea21.com"
 }

###

PUT http://localhost:8080/api/auth/activate/425d8dc1bb913f3e3e06ef19bc1840226e48fc9d
Content-Type: application/json  

###

PUT http://localhost:8080/api/auth/change-password
Content-Type: application/json

###

POST http://localhost:8080/api/auth/sign-in
Content-Type: application/json

{
    "username": "gorath71",
    "password": "Administrator1!"
}

###

POST http://localhost:8080/api/auth/sign-in
Content-Type: application/json

{
    "username": "gorath711",
    "password": "P@ssw0rd!123"
}

###

GET http://localhost:8080/api/auth/auth
Content-Type: application/json