POST http://localhost:8080/api/auth/sign-up
Content-Type: application/json

{
    "username": "gorath71",
    "email": "gorath@examdwplea2.com",
    "password": "P@ssw0rd!123",
    "accept_terms": true
}

###

PUT http://localhost:8080/api/auth/activation-link
Content-Type: application/json

 {
    "email": "gorath@examdwplea2.com"
 }

###

PUT http://localhost:8080/api/auth/activate/a6dd2fd2be95923863f733fede41c3032127ab7a
Content-Type: application/json  

###

PUT http://localhost:8080/api/auth/change-password
Content-Type: application/json