POST http://localhost:8080/api/authentication/signup
Content-Type: application/json

{
    "username": "user1aa",
    "email": "user@examplea2.com",
    "password": "Use434324524r!",
    "accept_terms": true
}

###

PUT http://localhost:8080/api/authentication/activate
Content-Type: application/json

 {
    "email": "user@examplea.com"
 }